"""Add unique constraint for asset, quote, and source

Revision ID: 88a7d904f91f
Revises: dcfdb77f0adf
Create Date: 2026-01-18 19:46:37.497134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a7d904f91f'
down_revision: Union[str, Sequence[str], None] = 'dcfdb77f0adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_asset_quote_source', 'crypto_price', ['asset', 'quote', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_quote_source', 'crypto_price', type_='unique')
    # ### end Alembic commands ###
